// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using APIApp.Client.Models;
using Newtonsoft.Json.Linq;

namespace APIApp.Client.Models
{
    public static partial class ArticleDTOCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ArticleDTO> DeserializeJson(JToken inputObject)
        {
            IList<ArticleDTO> deserializedObject = new List<ArticleDTO>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ArticleDTO articleDTO = new ArticleDTO();
                articleDTO.DeserializeJson(iListValue);
                deserializedObject.Add(articleDTO);
            }
            return deserializedObject;
        }
    }
}
